# Site settings
title: mdblandford.com
header-img: img/home-bg.png
email: mdblandford@gmail.com
copyright_name: mdblandford
description: > # this means to ignore newlines until "baseurl:"
  Curriculum blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mdblandford
learn_profile: mdblandford
email_username: mdblandford@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
